<?
$ruta_concurso2="http://".$_SERVER["SERVER_NAME"]."/varios/ms_wakeup/";
?>
<h3 class="widget-title sinopsis">SINOPSIS GENERAL</h3>

<div class="modulo_sin">
<img src="<?=$ruta_concurso2?>sinopsis.jpg" alt="">

<p>La madre de Abril decide rehacer su vida y comienza a convivir con Ricardo y su hijo, Marco. Este ensamble de familias  genera una tremenda crisis en la vida de Abril, nuestra protagonista.  Sin embargo cuando conoce a Marco, su “hermanastro”,  queda impactada. Él también se fascina con la fuerza de esa chica que arremete con todo para conseguir sus sueños. </p> 
<p>Abril descubre que su padre dejó en herencia una vieja estación de bomberos y su madre lo ha cedido a su hermanastro para que haga allí un centro comercial.  Él y Tomás, su mejor amigo,  están  asesorados por Ricardo, el padrastro de Abril, quién es el principal interesado en este proyecto. Pero  cuando Abril se entera, enfrenta a su madre dispuesta a recuperar lo que le corresponde. Entonces Clara y Ricardo le hacen una propuesta: le dejarán el espacio durante dos meses para que ella lo transforme en lo que quiera. Pero tendrá que ser un negocio, algo importante, no sólo un sueño de una chica de veinte años.</p>
<p>Abril decide animarse a este desafío. Y acompañada por sus tres amigos del alma, Celeste, Josefina y Alexis, resuelven armar un espacio cultural dónde confluyan todas las manifestaciones artísticas. Y además, el gran sueño que siempre tuvieron: armar su propia banda! </p>
<p>Pero pasado el primer entusiasmo se desmoralizan. La Estación está destruida y volverla un espacio donde poder desarrollar su proyecto requiere esfuerzo, un equipo de trabajo mayor,  y lo más difícil: dinero. Así que deciden convocar a un casting para armar la banda; una banda que además de tocar, pueda ser parte del proyecto de la Estación. </p>
<p>El casting es un éxito. Entre los aspirantes que llegan aparece Lady Ant, una artista muy talentosa, que se oculta “loockeándose” con raros peinados y vestimentas.  Lucas, un rockero excéntrico y provocador, y otros personajes increíbles como Jhonny, un cumbiero con mucho sex appeal, los hermanos Althmann: Manu y Kimei, que no son hermanos; Yahir, un lobo con piel de cordero que causará más de un problema a la banda; Erica, una chica tan despistada como talentosa;  y Laura que a pesar de su timidez rompe el escenario con su fuerza. </p>
<p>Por su parte Ricardo tiene que decirles a los inversionistas del centro comercial, que todo se va atrasar. A ellos no les gusta nada y amenazan a Ricardo, que comienza a preocuparse por ésta idea loca de Abril, sin poder compartirlo con Clara que no está al tanto de sus negociados.</p>




<p>Marco, cada día confía más en que Abril va a llevar a cabo su proyecto. Leticia comienza a sentir unos celos tremendos por Abril. Y también Tomás, que a pesar de estar en pareja con Martín, siempre estuvo enamorado de su mejor amigo. </p>
<p>Durante un evento que los chicos tienen que cubrir, el anfitrión de la fiesta, un músico muy importante,  escucha a Abril cantar y se queda impactado. Le hace un contacto con el manager de “La Cueva”, un lugar emblemático donde se hicieron famosas varias bandas muy importantes que ellos conocen. Abril no lo puede creer. ¡Cada día está más cerca de cumplir su sueño! </p>
<p>Mientras empiezan a ensayar para participar en “La Cueva” realizan su primer evento en la Estación, que es arruinado por una banda que irrumpe y hace su performance, eclipsando al público convocado. Son los Move Sing Move, que a partir de ese día serán la peor pesadilla para Abril y sus amigos.  Ese mismo día consiguen la fecha para su debut en “La Cueva”. Pero nada es tan fácil como parece, porque al volver descubren que la estación fue clausurada y todos sus equipos e instrumentos quedaron dentro. </p>
<p>Marco entrega todos sus ahorros para levantar la clausura. Clausura que fue instrumentada por Tomás y Ricardo. El gesto de Marco emociona a Abril que se lo agradece eternamente. A partir de acá, Marco y Abril se irán acercando cada día más. “Estación Colectiva”, nombre que inventa Alexis, se presenta en La Cueva. Pero la sorpresa se revela cuando el grupo oponente son los Move Sing Move. A pesar del impacto, los chicos hacen una buena actuación que los lleva a quedarse con el segundo puesto y una nueva posibilidad para competir. Pero la noche está llena de sorpresas. Abril descubre que Leticia es la líder de los Move Sing Move y la reta a una competencia limpia. Mientras tanto Ricardo, desesperado por la deuda que lo apremia, toma la decisión de hipotecar la Estación. Tomás no tarda en contarle la noticia a Leticia. Noticia de la que aún Abril no está enterada. Leticia, celosa de Abril porque Marco y ella están cada vez más juntos, decide hacer lo imposible por ganar y, en complicidad con Yahir, les roba la canción con la que Estación Colectiva se iría a presentar en la nueva competencia. Pero los chicos no se rinden y deciden salir a escena con otro tema que tenían ensayado. Cuando les toca el turno, Leticia intercepta a Abril y le da la noticia de que su Estación está hipotecada. Abril se marea, no lo puede creer, la noticia la deja tan descolocada que, aunque lo intente, no puede salir a escena. Pero Estación Colectiva no se rinde, no le pueden fallar a Abril, tienen que ser fuertes y cantan como nunca, tanto, que el público aplaude enfebrecido. Así, logran un empate con los Move Sing Move. Al día siguiente, Clara llega a la Estación para hablar con su hija e intenta explicarle que no quiso arruinarle la noche en La Cueva, que no esperaba que nadie, menos Leticia, se lo iría a contar. Dolida, pero entendiendo, Abril perdona a su madre y se reconcilian.</p> 

 <p>Esto le da fuerzas para ensayar para la gran final. Aunque todavía falta enfrentarse a alguien más. Creyendo que Marco fue cómplice de su padre, Abril se enoja con él, lo trata de traidor y Marco se queda impactado. Es evidente que Abril se equivocó y, arrepentida, vuelve a pedirle perdón. Pero el golpe ya fue dado. Marco no la perdona, no concibe que haya desconfiado así de él después de lo que hizo por ella. Pero el show debe seguir. La gran final llega. Los Move Sing Move hacen una perfomance excelente. Estación Colectiva tiene un rival muy difícil. Pero ellos tienen, además del talento, la amistad, la creencia en un sueño conjunto, tienen ganada el valor y el coraje por haberse enfrentado a tantos obstáculos, y todo esto les da la fuerza para salir a escena y brillar como nunca. Así, logran ganar la noche, llevarse el premio y triunfar. El sueño empieza a cumplirse, pero lo más importante es el aprendizaje que todo esto dejó en Abril. Ella se da cuenta que lo importante no es el lugar, la Estación; lo importante es lo que ellos construyeron juntos, la amistad que formaron, la banda que armaron. Lo tienen todo. Y no necesitan más. Abril “entrega” la Estación a Ricardo. Ella ya no la necesita. Solo necesita su “Estación Colectiva”.</p>


</div>